test_that("set_fontsize() works", {
  input1 <- matrix(1:10000, nrow = 10)
  expect_identical(CTexploreR:::set_fontsize(input1), 8)
  input2 <- matrix(1:10000, nrow = 25)
  expect_identical(CTexploreR:::set_fontsize(input2), 6)
  input3 <- matrix(1:10000, nrow = 80)
  expect_identical(CTexploreR:::set_fontsize(input3), 5)
  input4 <- matrix(1:10000, nrow = 125)
  expect_identical(CTexploreR:::set_fontsize(input4), 4)
  input5 <- matrix(1:10000, nrow = 200)
  expect_identical(CTexploreR:::set_fontsize(input5), 3)
  expect_error(CTexploreR:::set_fontsize())
  expect_error(CTexploreR:::set_fontsize("3"))
})
